import type { Metadata } from "next";
import { Figtree, Montserrat } from "next/font/google";
import "./globals.css";
import LoadingOverlay from "@/components/LoadingOverlay";

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
  display: "swap",
  weight: ["400", "600", "700", "800"],
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.variable} ${montserrat.variable} antialiased relative`}>
        <LoadingOverlay />
        {children}
      </body>
    </html>
  );
}
